name: Build and Deploy to S3

on:
  # mainブランチへのプッシュをトリガーにする
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main # リポジトリをチェックアウト

      - name: Install Dependecies
        run: num install
      
      - name: Build
        run: num run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --region ap-northeast-1 ./dist s3://github-actions-study --delete
          aws s3 cp --recursive --region ap-northeast-1 ./dist s3://github-actions-study