on:
  push:

env:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v1
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume:  arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ap-northeast-1
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: build
        run: npm run build
        working-directory: ./frontend

      - name: deploy
        run: aws s3 cp --recursive --region ap-northeast-1 dist/ s3://github-actions-study